# Generated by Django 5.2.16 on 2026-08-30 17:37

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('scripts', '0045_alter_scripttag_style'),
    ]

    operations = [
        # Built concurrently so this doesn't hold a table-level lock against
        # ScriptVersion for the duration of the build (the table is large and
        # is written to constantly by uploads/edits/votes in production).
        AddIndexConcurrently(
            model_name='scriptversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='sv_content_gin_idx'),
        ),
    ]
