# Generated by Django 5.2.17 on 2026-09-06 21:43

import scripts.slugs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0046_scriptversion_sv_content_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='slug',
            field=models.SlugField(blank=True, help_text="Optional custom id for this script, e.g. 'sects-and-violets'. Usable anywhere the numeric id is, so it cannot itself be a number. Leave blank for no slug.", null=True, unique=True, validators=[scripts.slugs.validate_script_slug]),
        ),
    ]
