# Generated by Django 5.2.17 on 2026-10-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0047_scriptversioncharacter'),
        ('scripts', '0052_shorten_status_labels'),
    ]

    operations = [
    ]
