# Generated by Django 5.2.17 on 2026-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0053_merge_upstream_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version_pk', models.IntegerField(help_text="The newest version id seen on botcscripts.com, in its numbering, not this site's.")),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpstreamVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_pk', models.IntegerField(help_text="The version's id on botcscripts.com.", unique=True)),
                ('script_id', models.IntegerField(help_text="Its script's id on botcscripts.com.")),
                ('row', models.JSONField()),
            ],
        ),
    ]
