# Generated by Django 5.2.17 on 2026-10-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0053_merge_upstream_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(help_text='Base URL of the instance, e.g. https://www.botcscripts.com', unique=True)),
                ('last_version_pk', models.IntegerField(help_text="The newest version id seen there, in that instance's numbering, not this one's.")),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
