# Generated by Django 5.2.17 on 2026-10-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0054_upstreamcursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('upstream_pk', models.IntegerField(help_text="The version's id there, unrelated to any id here.")),
                ('script_id', models.IntegerField(help_text="Its script's id there.")),
                ('row', models.JSONField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'upstream_pk'), name='unique_upstream_version')],
            },
        ),
    ]
