# Generated by Django 5.2.17 on 2026-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0054_upstream_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='minecraft_customisations',
            field=models.TextField(blank=True, default='', help_text='How the script is set up on the Minecraft server, e.g. its colour.'),
        ),
    ]
