# Generated by Django 5.2.17 on 2026-10-07 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0055_script_minecraft_customisations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='imported_by',
            field=models.ForeignKey(blank=True, help_text='Who imported it, if they were signed in. They may look after it as its owner may.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
