"""
Django settings for botc project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "scripts.apps.ScriptsConfig",
    "versionfield",
    "django_tables2",
    "django_filters",
    "bootstrap4",
    "django_bootstrap_icons",
    "rest_framework",
    "storages",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.discord",
    "markdownify.apps.MarkdownifyConfig",
    "corsheaders",
    "drf_spectacular",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "botc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
                "scripts.context_processors.custom_configuration",
            ],
        },
    }
]

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap4.html"

WSGI_APPLICATION = "botc.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = "c"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BotC Scripts API",
    "DESCRIPTION": "API for the www.botcscripts.com",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Session Settings
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": [
            'a',
            'abbr',
            'acronym',
            'b',
            "br",
            'blockquote',
            'em',
            "h1",
            "h2",
            "h3",
            'i',
            "img",
            'li',
            'ol',
            'p',
            'strong',
            'ul',
        ],
        "WHITELIST_ATTRS": [
            'href',
            'src',
            'alt',
        ],   
        "WHITELIST_STYLES": [
            'color',
            'font-weight',
        ],
        "WHITELIST_PROTOCOLS": [
            'https',
        ]        
    }
}

# django-allauth configuration
# No email is collected: nothing here sends mail, there is no password reset flow, and
# a self-hosted instance rarely has SMTP, so requiring an address only invites made-up
# ones. Login is therefore by username; allauth rejects email as a login method when
# email is not a signup field. Social accounts still carry whatever their provider
# supplies.
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Local username/password accounts, alongside the social providers. Signup closes
# independently of login, so an instance can invite by hand while existing users still
# get in. Verification defaults to none because a self-hosted instance rarely has SMTP;
# with the console backend a verification mail would only reach the container log.
ACCOUNT_ADAPTER = "scripts.adapters.LocalAccountAdapter"
LOCAL_SIGNUP_ENABLED = os.getenv("LOCAL_SIGNUP_ENABLED", "True") == "True"
ACCOUNT_EMAIL_VERIFICATION = os.getenv("ACCOUNT_EMAIL_VERIFICATION", "none")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

# Instances that anyone allowed to upload may also import from. Holders of
# scripts.api_write_permission are not held to this list; everybody else is, because
# importing makes THIS server fetch a URL the visitor supplied, so an unrestricted
# form open to all would be a way to aim it at anything the server can reach.
IMPORT_SOURCES = [
    source.strip()
    for source in os.getenv("IMPORT_SOURCES", "https://www.botcscripts.com").split(",")
    if source.strip()
]

# Arrivals: announcing new scripts and new versions to a Discord channel, through an
# incoming webhook. Blank switches arrivals off, which is the default. Treat the URL as a
# secret — anyone holding it can post to that channel.
DISCORD_ARRIVALS_WEBHOOK_URL = os.getenv("DISCORD_ARRIVALS_WEBHOOK_URL", "").strip()

# Prepended to each announcement so the right people see it, e.g. "<@&123456789012345678>"
# for a role, or "@here". Only the id named here is ever allowed to ping; a mention that
# happens to appear in a script's name is inert. See scripts/notifications.py.
DISCORD_ARRIVALS_WEBHOOK_MENTION = os.getenv("DISCORD_ARRIVALS_WEBHOOK_MENTION", "").strip()

# A second, separate webhook for when a version is marked as on the Minecraft server, so
# deployments can go to a different channel from arrivals. Independent of the arrivals
# webhook above: either, both or neither may be set. Same mention format.
DISCORD_ONLINE_WEBHOOK_URL = os.getenv("DISCORD_ONLINE_WEBHOOK_URL", "").strip()
DISCORD_ONLINE_WEBHOOK_MENTION = os.getenv("DISCORD_ONLINE_WEBHOOK_MENTION", "").strip()

# Absolute base for links in announcements. Nothing outside a request knows the site's own
# address, and the sync container never has one, so it is configured rather than derived.
# Left blank, the first CSRF trusted origin is used, which is the same public origin in
# any deployment that has one.
SITE_URL = os.getenv("SITE_URL", "").strip().rstrip("/")

# Allow CORS access to the API for GETs only.
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", False) == "True"
CORS_URLS_REGEX = r"^.*/api/.*$"
CORS_ALLOW_METHODS = "GET"

DISABLE_VALIDATORS = os.getenv("DISABLE_VALIDATORS", False) == "True"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local-cache',
    }
}